### ISSUE TITLE
Schemat elektryczny PCB

### ISSUE THREAD

**Issue by fifozof** [snasuddertale/Design-Lab-2022#1]
Zaprojektować schemat płytki integrujący raspberry pico z czujnikami oraz li-po

**Comment by piniondz** [comment]
Zamiast microSD weźmiemy zwykłe, bo są gotowe footprinty, a nie chce mi się szukać
https://botland.com.pl/akcesoria-do-kart-pamieci/1113-gniazdo-do-karty-pamieci-sd-z-wyrzutnikiem-sd238-5904422349318.html

**Comment by piniondz** [comment]
[LIB_SCD42-D-R2.zip](https://github.com/snasuddertale/Design-Lab-2022/files/9798198/LIB_SCD42-D-R2.zip)
[LIB_TGS3870-B00.zip](https://github.com/snasuddertale/Design-Lab-2022/files/9798201/LIB_TGS3870-B00.zip)
biblioteki do modeli

**Comment by fifozof** [comment]
[IC_Figaro_TGS5141-P00.zip](https://github.com/snasuddertale/Design-Lab-2022/files/9849215/IC_Figaro_TGS5141-P00.zip)
[LIB_MCP6V96UT-E_OT.zip](https://github.com/snasuddertale/Design-Lab-2022/files/9849214/LIB_MCP6V96UT-E_OT.zip)

**Comment by fifozof** [comment]
[tgs5141-p00_product infomation(en)_rev05.pdf](https://github.com/snasuddertale/Design-Lab-2022/files/9849478/tgs5141-p00_product.infomation.en._rev05.pdf)
[SHT3x-DIS.pdf](https://github.com/snasuddertale/Design-Lab-2022/files/9849479/SHT3x-DIS.pdf)
