### ISSUE TITLE
Projekt płytki PCB

### ISSUE THREAD

**Issue by fifozof** [snasuddertale/Design-Lab-2022#2]
Zaadaptować schemat elektryczny na projekt płytki

**Comment by piniondz** [comment]
USB type C PD unit:
[https://kamami.pl/wyzwalacze-usb-pd/584719-wyzwalacz-pd-usb-typu-c-5-20v-5a-bez-zlacza.html](url)

**Comment by piniondz** [comment]
Step down converters:
[https://kamami.pl/step-down/1180785-tlv62569-33v-buck-converter-przetwornica-dc-dc-step-down-33v-12a-4711.html](url)
[https://kamami.pl/step-down/584843-dc-dc-buck-converter-modul-przetwornicy-dc-dc-step-down-5v-4a-dfr0831.html](url)

**Comment by fifozof** [comment]
https://docs.google.com/spreadsheets/d/1wi3Lu7qkAkqb2vKT01jeF7vUba7tjb3UAKRYJopAfTQ/edit?usp=sharing

**Comment by fifozof** [comment]
https://sklep.avt.pl/obudowa-plastikowa-z78-43x85x154-jasna.html
